### ISSUE TITLE
Please include previous git history

### ISSUE THREAD

**Issue by jonte** [Pelagicore/bluetooth-demo#2]
Hi,

It seems like the commit history in this repository has been squashed into one commit. I think there is value in the history, and I would prefer if the history was preserved. The history will, for instance, make it easier to understand when a feature was added, and who to `git blame` to discuss why it was added.

I can push the complete history if that helps.

**Comment by GordanM** [comment]
+1

**Comment by jeremiah** [comment]
Yes, I anticipated this issue but wanted to complete launching the code. While pulling from our internal git I had issues using git clone since I need a new VPN (our internal IP address scheme changed) and have to debug ssh key issues (despite having a previously working key.) 

In short; @jonte can I ask you to push the history?

**Comment by jonte** [comment]
@jeremiah Done!

I also renamed the repo to blueConnect. This should cause no issues when cloning / pushing to the old URI, since the old URI is kept intact by GitHub.
